// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID        int32     `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户ID" json:"user_id"` // 用户ID
	Nickname      string    `gorm:"column:nickname;not null;comment:用户名" json:"nickname"`                     // 用户名
	Avatar        string    `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                          // 头像
	Password      string    `gorm:"column:password;not null;comment:用户密码 des/md5加密值" json:"password"`         // 用户密码 des/md5加密值
	Phone         string    `gorm:"column:phone;not null;comment:手机号 aes加密" json:"phone"`                     // 手机号 aes加密
	Gender        int32     `gorm:"column:gender;not null;default:9;comment:性别 0|男、1|女、9|未知" json:"gender"`   // 性别 0|男、1|女、9|未知
	Status        int32     `gorm:"column:status;not null;comment:状态 0|正常、1|注销、2|冻结" json:"status"`           // 状态 0|正常、1|注销、2|冻结
	RegisterIP    string    `gorm:"column:register_ip;not null" json:"register_ip"`
	RegisterTime  time.Time `gorm:"column:register_time;not null;default:CURRENT_TIMESTAMP" json:"register_time"`
	LastLoginIP   string    `gorm:"column:last_login_ip;not null" json:"last_login_ip"`
	LastLoginTime time.Time `gorm:"column:last_login_time;not null;default:CURRENT_TIMESTAMP" json:"last_login_time"`
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
