package metadata

const NotEditMark = `
// Code generated by jasonlabz/gentol. DO NOT EDIT.

`

type IBaseData interface {
	GenRenderData() map[string]any
}

type MetaType struct {
	GoType             string
	SQLNullableType    string
	GureguNullableType string
}

type BaseConfig struct {
	DBType                string
	SchemaName            string
	TableName             string
	DSN                   string
	OnlyModel             bool
	ServicePath           string
	ModelPath             string
	DaoPath               string
	JsonFormat            string
	XMLFormat             string
	ProtobufFormat        string
	RunGoFmt              bool
	UseSQLNullable        bool
	AddGormAnnotation     bool
	AddProtobufAnnotation bool
}
