// Code generated by jasonlabz/gentol. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"github.com/guregu/null"
	"github.com/satori/go.uuid"
)

var (
	_ = time.Second
	_ = sql.LevelDefault
	_ = null.Bool{}
	_ = uuid.UUID{}
)

const TableNameUser = "public.user"

type UserField string

const (
	USER_USER_ID UserField = "user_id"

	USER_NICKNAME UserField = "nickname"

	USER_AVATAR UserField = "avatar"

	USER_PASSWORD UserField = "password"

	USER_PHONE UserField = "phone"

	USER_GENDER UserField = "gender"

	USER_STATUS UserField = "status"

	USER_REGISTER_IP UserField = "register_ip"

	USER_REGISTER_TIME UserField = "register_time"

	USER_LAST_LOGIN_IP UserField = "last_login_ip"

	USER_LAST_LOGIN_TIME UserField = "last_login_time"

	USER_CREATE_TIME UserField = "create_time"

	USER_UPDATE_TIME UserField = "update_time"
)

// User struct is mapping to the user table
type User struct {
	UserID int32 `gorm:"primary_key;auto_increment;column:user_id;type:int4;size:32;" json:"user_id"` // Comment: 用户ID

	Nickname string `gorm:"column:nickname;type:varchar;size:255;" json:"nickname"` // Comment: 用户名

	Avatar string `gorm:"column:avatar;type:varchar;size:255;" json:"avatar"` // Comment: 头像

	Password string `gorm:"column:password;type:varchar;size:255;" json:"password"` // Comment: 用户密码 des/md5加密值

	Phone string `gorm:"column:phone;type:varchar;size:255;default:'';" json:"phone"` // Comment: 手机号 aes加密

	Gender int32 `gorm:"column:gender;type:int4;size:32;default:9;" json:"gender"` // Comment: 性别 0|男、1|女、9|未知

	Status int32 `gorm:"column:status;type:int4;size:32;default:0;" json:"status"` // Comment: 状态 0|正常、1|注销、2|冻结

	RegisterIP string `gorm:"column:register_ip;type:varchar;size:255;" json:"register_ip"` // Comment: no comment

	RegisterTime time.Time `gorm:"column:register_time;type:timestamp;size:64;default:CURRENT_TIMESTAMP;" json:"register_time"` // Comment: no comment

	LastLoginIP string `gorm:"column:last_login_ip;type:varchar;size:255;" json:"last_login_ip"` // Comment: no comment

	LastLoginTime time.Time `gorm:"column:last_login_time;type:timestamp;size:64;default:CURRENT_TIMESTAMP;" json:"last_login_time"` // Comment: no comment

	CreateTime time.Time `gorm:"column:create_time;type:timestamp;size:64;default:CURRENT_TIMESTAMP;" json:"create_time"` // Comment: no comment

	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;size:64;default:CURRENT_TIMESTAMP;" json:"update_time"` // Comment: no comment
}
